// Objeto con los 15 idiomas requeridos para el grupo SASA
const DICTIONARY = {
    es: {
        page_title: "BENEATH - Archivos Seguros & Control Gerencial // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "Bienvenido al Grupo SASA",
        welcome_desc: "Infraestructura protegida y cifrada. Ningún dato telefónico o personal es expuesto.",
        access_btn: "Acceder al Sistema",
        page_title: "BENEATH - Archivos Seguros & Control Gerencial // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "PANTALLA PROTEGIDA",
        curtain_desc: "La sesión ha sido ocultada por seguridad visual en oficina.",
        curtain_btn: "Restaurar Pantalla",
        app_subtitle: "TRANSMITIR • ARCHIVOS EFÍMEROS • AUDITAR",
        setup_title: "Crear Identidad Local",
        label_pin: "Define un PIN de Acceso (4 dígitos)",
        setup_btn: "Iniciar BENEATH y Generar Llaves",
        active_identity_label: "Identidad activa:",
        enter_pin_label: "Introduce tu PIN",
        unlock_pin_btn: "Desbloquear (PIN)",
        forgot_pin_link: "¿Olvidaste tu PIN? (Frase de Rescate)",
        recovery_title: "Rescate de Cero-Conocimiento",
        recovery_desc: "Introduce tu frase secreta de emergencia:",
        recovery_btn: "Restablecer Acceso",
        hide_btn: "👁️ Ocultar",
        back_btn: "🚪 Regresar",
        active_groups_title: "Tus Grupos Activos",
        group_desc_pesa: "Canal Seguro Unificado (72h)",
        enter_group_btn: "Entrar &rarr;",
        back_to_groups_btn: "&larr; Volver a Grupos",
        audit_members_btn: "📊 Auditoría & Miembros",
        msg_placeholder: "Escribir mensaje o pegar link (Enter)...",
        send_btn: "Enviar",
        attach_file_label: "📎 Adjuntar Archivo / Foto / PDF (Vista In-App)",
        select_file_btn: "Seleccionar Archivo",
        close_btn: "✕ Cerrar",
        alert_invalid_identity: "Por favor escribe una identidad válida y un PIN exacto de 4 dígitos.",
        alert_revoked: "Tu acceso ha sido revocado por el administrador.",
        alert_identity_created: "¡Identidad creada con éxito!\n\n[ FRASE DE RESCATE DE EMERGENCIA ]\nAnota estas 4 palabras:\n\n--> ${frase} <--",
        alert_wrong_pin: "PIN incorrecto.",
        alert_phrase_verified: "¡Frase verificada! Establece un nuevo PIN.",
        prompt_new_pin: "Introduce tu nuevo PIN de 4 dígitos:",
        alert_pin_updated: "PIN actualizado. Entrando...",
        alert_invalid_pin: "PIN no válido.",
        alert_wrong_phrase: "Frase incorrecta.",
        audit_panel_title: "Panel de Control Gerencial & Miembros",
        audit_full_access: "Acceso Total",
        audit_status_expelled: "Expulsado / Revocado",
        audit_status_active: "Activo",
        audit_btn_readmit: "Readmitir",
        audit_btn_expel: "Expulsar",
        audit_director: "Director",
        audit_confirm_expel: "¿Estás seguro de expulsar a ${nombreMiembro}? Su sesión se cerrará de inmediato y no podrá acceder.",
        chat_none_yet: "Ninguno aún",
        chat_audit_seen_by: "Auditoría Gerencial - Visto por:",
        chat_delete_title: "Eliminar contenido",
        chat_expires_in: "Expira en 72h (Autodestrucción)",
        chat_secure_file: "Archivo Seguro",
        chat_transmitted: "Transmitido",
        viewer_zero_trace_img: "🛡️ Modo Zero-Trace Activo: Imagen protegida contra descarga directa.",
        viewer_zero_trace_pdf: "🛡️ Modo Zero-Trace Activo: Visualización de documento restringida a memoria.",
        viewer_restricted_format: "Este formato se visualiza de forma restringida.",
        recovery_placeholder: "palabra1 palabra2 palabra3 palabra4",
role_prefix: "ROL:",
hide_tooltip: "Bloqueo Exprés",
back_tooltip: "Regresar a pantalla de bloqueo",
role_admin: "ADMIN / DIRECTOR",
role_member: "INTEGRANTE",
btn_view: "Ver",
btn_download: "Descargar",
label_identity: "Tu Nombre de Identidad (El primero configurado será Admin)",
placeholder_identity: "Ej. LUNA o TIGRE"
    },
    en: {
        page_title: "BENEATH - Secure Files & Management Control // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "Welcome to SASA Group",
        welcome_desc: "Protected and encrypted infrastructure. No telephone or personal data is exposed.",
        access_btn: "Access System",
        page_title: "BENEATH - Secure Files & Management Control // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "PROTECTED SCREEN",
        curtain_desc: "The session has been hidden for office visual security.",
        curtain_btn: "Restore Screen",
        app_subtitle: "TRANSMIT • EPHEMERAL FILES • AUDIT",
        setup_title: "Create Local Identity",
        label_pin: "Define an Access PIN (4 digits)",
        setup_btn: "Start BENEATH and Generate Keys",
        active_identity_label: "Active identity:",
        enter_pin_label: "Enter your PIN",
        unlock_pin_btn: "Unlock (PIN)",
        forgot_pin_link: "Forgot your PIN? (Recovery Phrase)",
        recovery_title: "Zero-Knowledge Recovery",
        recovery_desc: "Enter your emergency secret phrase:",
        recovery_btn: "Reset Access",
        hide_btn: "👁️ Hide",
        back_btn: "🚪 Back",
        active_groups_title: "Your Active Groups",
        group_desc_pesa: "Unified Secure Channel (72h)",
        enter_group_btn: "Enter &rarr;",
        back_to_groups_btn: "&larr; Back to Groups",
        audit_members_btn: "📊 Audit & Members",
        msg_placeholder: "Type message or paste link (Enter)...",
        send_btn: "Send",
        attach_file_label: "📎 Attach File / Photo / PDF (In-App View)",
        select_file_btn: "Select File",
        close_btn: "✕ Close",
        alert_invalid_identity: "Please enter a valid identity and an exact 4-digit PIN.",
        alert_revoked: "Your access has been revoked by the administrator.",
        alert_identity_created: "Identity successfully created!\n\n[ EMERGENCY RECOVERY PHRASE ]\nWrite down these 4 words:\n\n--> ${frase} <--",
        alert_wrong_pin: "Incorrect PIN.",
        alert_phrase_verified: "Phrase verified! Set a new PIN.",
        prompt_new_pin: "Enter your new 4-digit PIN:",
        alert_pin_updated: "PIN updated. Entering...",
        alert_invalid_pin: "Invalid PIN.",
        alert_wrong_phrase: "Incorrect phrase.",
        audit_panel_title: "Management Control Panel & Members",
        audit_full_access: "Full Access",
        audit_status_expelled: "Expelled / Revoked",
        audit_status_active: "Active",
        audit_btn_readmit: "Readmit",
        audit_btn_expel: "Expel",
        audit_director: "Director",
        audit_confirm_expel: "Are you sure you want to expel ${nombreMiembro}? Their session will be closed immediately and they won't be able to access.",
        chat_none_yet: "None yet",
        chat_audit_seen_by: "Management Audit - Seen by:",
        chat_delete_title: "Delete content",
        chat_expires_in: "Expires in 72h (Self-destruction)",
        chat_secure_file: "Secure File",
        chat_transmitted: "Transmitted",
        viewer_zero_trace_img: "🛡️ Zero-Trace Mode Active: Image protected against direct download.",
        viewer_zero_trace_pdf: "🛡️ Zero-Trace Mode Active: Document viewing restricted to memory.",
        viewer_restricted_format: "This format is displayed in a restricted manner.",
        recovery_placeholder: "word1 word2 word3 word4",
role_prefix: "ROLE:",
hide_tooltip: "Express Lock",
back_tooltip: "Return to lock screen",
role_admin: "ADMIN / DIRECTOR",
role_member: "MEMBER",
btn_view: "View",
btn_download: "Download",
label_identity: "Your Identity Name (The first configured will be Admin)",
placeholder_identity: "Ex. MOON or TIGER"
    },
    pt: {
        page_title: "BENEATH - Arquivos Seguros & Controle Gerencial // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "Bem-vindo ao Grupo SASA",
        welcome_desc: "Infraestrutura protegida e criptografada. Nenhum dado telefônico ou pessoal é exposto.",
        access_btn: "Acessar o Sistema",
        page_title: "BENEATH - Arquivos Seguros & Controle Gerencial // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "TELA PROTEGIDA",
        curtain_desc: "A sessão foi ocultada por segurança visual no escritório.",
        curtain_btn: "Restaurar Tela",
        app_subtitle: "TRANSMITIR • ARQUIVOS EFÊMEROS • AUDITAR",
        setup_title: "Criar Identidade Local",
        label_pin: "Defina um PIN de Acesso (4 dígitos)",
        setup_btn: "Iniciar BENEATH e Gerar Chaves",
        active_identity_label: "Identidade ativa:",
        enter_pin_label: "Digite seu PIN",
        unlock_pin_btn: "Desbloquear (PIN)",
        forgot_pin_link: "Esqueceu seu PIN? (Frase de Recuperação)",
        recovery_title: "Recuperação de Conhecimiento Zero",
        recovery_desc: "Digite sua frase secreta de emergência:",
        recovery_btn: "Redefinir Acesso",
        hide_btn: "👁️ Ocultar",
        back_btn: "🚪 Voltar",
        active_groups_title: "Seus Grupos Ativos",
        group_desc_pesa: "Canal Seguro Unificado (72h)",
        enter_group_btn: "Entrar &rarr;",
        back_to_groups_btn: "&larr; Voltar para Grupos",
        audit_members_btn: "📊 Auditoria & Membros",
        msg_placeholder: "Digite mensagem ou cole link (Enter)...",
        send_btn: "Enviar",
        attach_file_label: "📎 Anexar Arquivo / Foto / PDF (Visualização In-App)",
        select_file_btn: "Selecionar Arquivo",
        close_btn: "✕ Fechar",
        alert_invalid_identity: "Por favor, insira uma identidade válida e um PIN exato de 4 dígitos.",
        alert_revoked: "Seu acesso foi revogado pelo administrador.",
        alert_identity_created: "Identidade criada com sucesso!\n\n[ FRASE DE RECUPERAÇÃO DE EMERGÊNCIA ]\nAnote estas 4 palavras:\n\n--> ${frase} <--",
        alert_wrong_pin: "PIN incorreto.",
        alert_phrase_verified: "Frase verificada! Defina um novo PIN.",
        prompt_new_pin: "Digite seu novo PIN de 4 dígitos:",
        alert_pin_updated: "PIN atualizado. Entrando...",
        alert_invalid_pin: "PIN inválido.",
        alert_wrong_phrase: "Frase incorreta.",
        audit_panel_title: "Painel de Controle Gerencial & Membros",
        audit_full_access: "Acesso Total",
        audit_status_expelled: "Expulso / Revogado",
        audit_status_active: "Ativo",
        audit_btn_readmit: "Readmitir",
        audit_btn_expel: "Expulsar",
        audit_director: "Diretor",
        audit_confirm_expel: "Tem certeza de que deseja expulsar ${nombreMiembro}? A sessão dele será encerrada imediatamente e ele não poderá acessar.",
        chat_none_yet: "Nenhum ainda",
        chat_audit_seen_by: "Auditoria Gerencial - Visto por:",
        chat_delete_title: "Excluir conteúdo",
        chat_expires_in: "Expira em 72h (Autodestruição)",
        chat_secure_file: "Arquivo Seguro",
        chat_transmitted: "Transmitido",
        viewer_zero_trace_img: "🛡️ Modo Zero-Trace Ativo: Imagem protegida contra download direto.",
        viewer_zero_trace_pdf: "🛡️ Modo Zero-Trace Ativo: Visualização de documentos restrita à memória.",
        viewer_restricted_format: "Este formato é exibido de forma restrita.",
        recovery_placeholder: "palavra1 palavra2 palavra3 palavra4",
role_prefix: "FUNÇÃO:",
hide_tooltip: "Bloqueio Express",
back_tooltip: "Voltar para a tela de bloqueio",
role_admin: "ADMIN / DIRETOR",
role_member: "MEMBRO",
btn_view: "Ver",
btn_download: "Baixar",
label_identity: "Seu Nome de Identidade (O primeiro configurado será Admin)",
placeholder_identity: "Ex. LUA ou TIGRE"
    },
    fr: {
        page_title: "BENEATH - Fichiers Sécurisés & Contrôle de Gestion // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "Bienvenue dans le Groupe SASA",
        welcome_desc: "Infrastructure protégée et chiffrée. Aucune donnée téléphonique ou personnelle n'est exposée.",
        access_btn: "Accéder au Système",
        page_title: "BENEATH - Fichiers Sécurisés & Contrôle de Gestion // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "ÉCRAN PROTÉGÉ",
        curtain_desc: "La session a été masquée pour des raisons de sécurité visuelle au bureau.",
        curtain_btn: "Restaurer l'écran",
        app_subtitle: "TRANSMETTRE • FICHIERS ÉPHÉMÈRES • AUDITER",
        setup_title: "Créer une Identité Locale",
        label_pin: "Définissez un PIN d'accès (4 chiffres)",
        setup_btn: "Démarrer BENEATH et Générer les Clés",
        active_identity_label: "Identité active :",
        enter_pin_label: "Entrez votre PIN",
        unlock_pin_btn: "Déverrouiller (PIN)",
        forgot_pin_link: "Mot de passe oublié ? (Phrase de récupération)",
        recovery_title: "Récupération Zero-Knowledge",
        recovery_desc: "Entrez votre phrase secrète d'urgence :",
        recovery_btn: "Réinitialiser l'accès",
        hide_btn: "👁️ Masquer",
        back_btn: "🚪 Retour",
        active_groups_title: "Vos Groupes Actifs",
        group_desc_pesa: "Canal Sécurisé Unifié (72h)",
        enter_group_btn: "Entrer &rarr;",
        back_to_groups_btn: "&larr; Retour aux Groupes",
        audit_members_btn: "📊 Audit & Membres",
        msg_placeholder: "Écrire un message ou coller un lien (Enter)...",
        send_btn: "Envoyer",
        attach_file_label: "📎 Joindre Fichier / Photo / PDF (Vue In-App)",
        select_file_btn: "Sélectionner un fichier",
        close_btn: "✕ Fermer",
        alert_invalid_identity: "Veuillez entrer une identité valide et un PIN exact à 4 chiffres.",
        alert_revoked: "Votre accès a été révoqué par l'administrateur.",
        alert_identity_created: "Identité créée avec succès !\n\n[ PHRASE DE RÉCUPÉRATION D'URGENCE ]\nNotez ces 4 mots :\n\n--> ${frase} <--",
        alert_wrong_pin: "PIN incorrect.",
        alert_phrase_verified: "Phrase vérifiée ! Définissez un nouveau PIN.",
        prompt_new_pin: "Entrez votre nouveau PIN à 4 chiffres :",
        alert_pin_updated: "PIN mis à jour. Connexion...",
        alert_invalid_pin: "PIN invalide.",
        alert_wrong_phrase: "Phrase incorrecte.",
        audit_panel_title: "Panneau de Contrôle de Gestion & Membres",
        audit_full_access: "Accès Total",
        audit_status_expelled: "Expulsé / Révoqué",
        audit_status_active: "Actif",
        audit_btn_readmit: "Réadmettre",
        audit_btn_expel: "Expulser",
        audit_director: "Directeur",
        audit_confirm_expel: "Êtes-vous sûr d'expulser ${nombreMiembro} ? Sa session sera fermée immédiatement et il ne pourra plus accéder.",
        chat_none_yet: "Aucun pour l'instant",
        chat_audit_seen_by: "Audit de Gestion - Vu par :",
        chat_delete_title: "Supprimer le contenu",
        chat_expires_in: "Expire dans 72h (Autodestruction)",
        chat_secure_file: "Fichier Sécurisé",
        chat_transmitted: "Transmis",
        viewer_zero_trace_img: "🛡️ Mode Zero-Trace Actif : Image protégée contre le téléchargement direct.",
        viewer_zero_trace_pdf: "🛡️ Mode Zero-Trace Actif : Visualisation du document restreinte à la mémoire.",
        viewer_restricted_format: "Ce format est affiché de manière restreinte.",
        recovery_placeholder: "mot1 mot2 mot3 mot4",
role_prefix: "RÔLE:",
hide_tooltip: "Verrouillage Express",
back_tooltip: "Retour à l'écran de verrouillage",
role_admin: "ADMIN / DIRECTEUR",
role_member: "MEMBRE",
btn_view: "Voir",
btn_download: "Télécharger",
label_identity: "Votre Nom d'Identité (Le premier configuré sera Admin)",
placeholder_identity: "Ex. LUNE ou TIGRE"
    },
    de: {
        page_title: "BENEATH - Sichere Dateien & Management-Kontrolle // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "Willkommen in der SASA-Gruppe",
        welcome_desc: "Geschützte und verschlüsselte Infrastruktur. Es werden keine Telefon- oder persönlichen Daten preisgegeben.",
        access_btn: "System Aufrufen",
        page_title: "BENEATH - Sichere Dateien & Management-Kontrolle // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "GESCHÜTZTER BILDSCHIRM",
        curtain_desc: "Die Sitzung wurde aus Gründen der visuellen Sicherheit im Büro ausgeblendet.",
        curtain_btn: "Bildschirm Wiederherstellen",
        app_subtitle: "ÜBERTRAGEN • EPHEMERE DATEIEN • PRÜFEN",
        setup_title: "Lokale Identität Erstellen",
        label_pin: "Definieren Sie eine PIN (4 Ziffern)",
        setup_btn: "BENEATH Starten & Schlüssel Generieren",
        active_identity_label: "Aktive Identität:",
        enter_pin_label: "Geben Sie Ihre PIN ein",
        unlock_pin_btn: "Entsperren (PIN)",
        forgot_pin_link: "PIN vergessen? (Wiederherstellungsphrase)",
        recovery_title: "Zero-Knowledge-Wiederherstellung",
        recovery_desc: "Geben Sie Ihre geheime Notfallphrase ein:",
        recovery_btn: "Zugang zurücksetzen",
        hide_btn: "👁️ Verstecken",
        back_btn: "🚪 Zurück",
        active_groups_title: "Ihre Aktiven Gruppen",
        group_desc_pesa: "Einheitlicher sicherer Kanal (72h)",
        enter_group_btn: "Eintreten &rarr;",
        back_to_groups_btn: "&larr; Zurück zu Gruppen",
        audit_members_btn: "📊 Audit & Mitglieder",
        msg_placeholder: "Nachricht schreiben oder Link einfügen (Enter)...",
        send_btn: "Senden",
        attach_file_label: "📎 Datei / Foto / PDF anhängen (In-App-Ansicht)",
        select_file_btn: "Datei auswählen",
        close_btn: "✕ Schließen",
        alert_invalid_identity: "Bitte geben Sie eine gültige Identität und eine exakte 4-stellige PIN ein.",
        alert_revoked: "Ihr Zugriff wurde vom Administrator widerrufen.",
        alert_identity_created: "Identität erfolgreich erstellt!\n\n[ NOTFALL-WIEDERHERSTELLUNGSPHRASE ]\nNotieren Sie sich diese 4 Wörter:\n\n--> ${frase} <--",
        alert_wrong_pin: "Falsche PIN.",
        alert_phrase_verified: "Phrase verifiziert! Legen Sie eine neue PIN fest.",
        prompt_new_pin: "Geben Sie Ihre neue 4-stellige PIN ein:",
        alert_pin_updated: "PIN aktualisiert. Anmeldung...",
        alert_invalid_pin: "Ungültige PIN.",
        alert_wrong_phrase: "Falsche Phrase.",
        audit_panel_title: "Management-Kontrollpanel & Mitglieder",
        audit_full_access: "Vollzugriff",
        audit_status_expelled: "Ausgeschlossen / Widerrufen",
        audit_status_active: "Aktiv",
        audit_btn_readmit: "Wieder zulassen",
        audit_btn_expel: "Ausschließen",
        audit_director: "Direktor",
        audit_confirm_expel: "Sind Sie sicher, dass Sie ${nombreMiembro} ausschließen möchten? Ihre Sitzung wird sofort beendet und sie können nicht mehr zugreifen.",
        chat_none_yet: "Noch keiner",
        chat_audit_seen_by: "Management-Audit - Gesehen von:",
        chat_delete_title: "Inhalt löschen",
        chat_expires_in: "Läuft in 72h ab (Selbstzerstörung)",
        chat_secure_file: "Sichere Datei",
        chat_transmitted: "Übertragen",
        viewer_zero_trace_img: "🛡️ Zero-Trace-Modus aktiv: Bild vor direktem Download geschützt.",
        viewer_zero_trace_pdf: "🛡️ Zero-Trace-Modus aktiv: Dokumentenanzeige auf den Speicher beschränkt.",
        viewer_restricted_format: "Dieses Format wird eingeschränkt angezeigt.",
        recovery_placeholder: "wort1 wort2 wort3 wort4",
role_prefix: "ROLLE:",
hide_tooltip: "Express-Sperre",
back_tooltip: "Zurück zum Sperrbildschirm",
role_admin: "ADMIN / DIREKTOR",
role_member: "MITGLIED",
btn_view: "Ansehen",
btn_download: "Herunterladen",
label_identity: "Ihr Identitätsname (Der zuerst konfigurierte wird Admin)",
placeholder_identity: "Bsp. MOND oder TIGER"
    },
    ko: {
        page_title: "BENEATH - 보안 파일 및 관리 제어 // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "SASA 그룹에 오신 것을 환영합니다",
        welcome_desc: "보호 및 암호화된 인프라입니다. 전화번호나 개인정보는 노출되지 않습니다.",
        access_btn: "시스템 접속",
        page_title: "BENEATH - 보안 파일 및 관리 제어 // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "보호된 화면",
        curtain_desc: "사무실 시각적 보안을 위해 세션이 숨겨졌습니다.",
        curtain_btn: "화면 복원",
        app_subtitle: "전송 • 임시 파일 • 감사",
        setup_title: "로컬 ID 생성",
        label_pin: "액세스 PIN 정의 (4자리)",
        setup_btn: "BENEATH 시작 및 키 생성",
        active_identity_label: "활성 ID:",
        enter_pin_label: "PIN 입력",
        unlock_pin_btn: "잠금 해제 (PIN)",
        forgot_pin_link: "PIN을 잊으셨습니까? (복구 구문)",
        recovery_title: "영지식 복구",
        recovery_desc: "비상 비밀 구문을 입력하세요:",
        recovery_btn: "접속 재설정",
        hide_btn: "👁️ 숨기기",
        back_btn: "🚪 뒤로",
        active_groups_title: "활성 그룹",
        group_desc_pesa: "통합 보안 채널 (72시간)",
        enter_group_btn: "입장 &rarr;",
        back_to_groups_btn: "&larr; 그룹으로 돌아가기",
        audit_members_btn: "📊 감사 및 회원",
        msg_placeholder: "메시지 작성 또는 링크 붙여넣기 (Enter)...",
        send_btn: "보내기",
        attach_file_label: "📎 파일 / 사진 / PDF 첨부 (앱 내 보기)",
        select_file_btn: "파일 선택",
        close_btn: "✕ 닫기",
        alert_invalid_identity: "유효한 ID와 정확히 4자리 PIN을 입력하세요.",
        alert_revoked: "관리자에 의해 접근이 취소되었습니다.",
        alert_identity_created: "신원이 성공적으로 생성되었습니다!\n\n[ 긴급 복구 문구 ]\n다음 4단어를 적어두세요:\n\n--> ${frase} <--",
        alert_wrong_pin: "잘못된 PIN입니다.",
        alert_phrase_verified: "문구가 확인되었습니다! 새 PIN을 설정하세요.",
        prompt_new_pin: "새 4자리 PIN을 입력하세요:",
        alert_pin_updated: "PIN이 업데이트되었습니다. 입장 중...",
        alert_invalid_pin: "유효하지 않은 PIN입니다.",
        alert_wrong_phrase: "잘못된 문구입니다.",
        audit_panel_title: "경영 제어판 및 회원",
        audit_full_access: "전체 접근 권한",
        audit_status_expelled: "추방됨 / 취소됨",
        audit_status_active: "활성",
        audit_btn_readmit: "재가입 허용",
        audit_btn_expel: "추방",
        audit_director: "이사",
        audit_confirm_expel: "${nombreMiembro}님을 추방하시겠습니까? 세션이 즉시 종료되며 더 이상 접근할 수 없습니다.",
        chat_none_yet: "아직 없음",
        chat_audit_seen_by: "경영 감사 - 확인한 사람:",
        chat_delete_title: "콘텐츠 삭제",
        chat_expires_in: "72시간 후 만료 (자체 파괴)",
        chat_secure_file: "보안 파일",
        chat_transmitted: "전송됨",
        viewer_zero_trace_img: "🛡️ 제로 트레이스 모드 활성화: 직접 다운로드로부터 보호되는 이미지.",
        viewer_zero_trace_pdf: "🛡️ 제로 트레이스 모드 활성화: 메모리로 제한된 문서 보기.",
        viewer_restricted_format: "이 형식은 제한된 방식으로 표시됩니다.",
        recovery_placeholder: "단어1 단어2 단어3 단어4",
role_prefix: "역할:",
hide_tooltip: "빠른 잠금",
back_tooltip: "잠금 화면으로 돌아가기",
role_admin: "관리자 / 디렉터",
role_member: "회원",
btn_view: "보기",
btn_download: "다운로드",
label_identity: "아이덴티티 이름 (처음 설정된 사람이 관리자가 됨)",
placeholder_identity: "예: LUNA 또는 TIGRE"
    },
    zh: {
        page_title: "BENEATH - 安全文件与管理控制 // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "欢迎加入 SASA 团队",
        welcome_desc: "受保护的加密基础设施。不会泄露任何电话或个人数据。",
        access_btn: "访问系统",
        page_title: "BENEATH - 安全文件与管理控制 // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "受保护的屏幕",
        curtain_desc: "出于办公室视觉安全考虑，会话已被隐藏。",
        curtain_btn: "恢复屏幕",
        app_subtitle: "传输 • 临时文件 • 审计",
        setup_title: "创建本地身份",
        label_pin: "设置访问 PIN（4位数）",
        setup_btn: "启动 BENEATH 并生成密钥",
        active_identity_label: "当前身份：",
        enter_pin_label: "输入您的 PIN 码",
        unlock_pin_btn: "解锁 (PIN)",
        forgot_pin_link: "忘记 PIN 码？（恢复短语）",
        recovery_title: "零知识恢复",
        recovery_desc: "输入您的紧急安全短语：",
        recovery_btn: "重置访问权限",
        hide_btn: "👁️ 隐藏",
        back_btn: "🚪 返回",
        active_groups_title: "您的活跃群组",
        group_desc_pesa: "统一安全通道 (72小时)",
        enter_group_btn: "进入 &rarr;",
        back_to_groups_btn: "&larr; 返回群组",
        audit_members_btn: "📊 审计与成员",
        msg_placeholder: "输入消息或粘贴链接 (Enter)...",
        send_btn: "发送",
        attach_file_label: "📎 附加文件 / 照片 / PDF (应用内查看)",
        select_file_btn: "选择文件",
        close_btn: "✕ 关闭",
        alert_invalid_identity: "请输入有效的身份名称和一个4位数的 PIN 码。",
        alert_revoked: "您的访问权限已被管理员撤销。",
        alert_identity_created: "身份创建成功！\n\n[ 紧急恢复短语 ]\n请记下这 4 个词：\n\n--> ${frase} <--",
        alert_wrong_pin: "PIN 码错误。",
        alert_phrase_verified: "短语已验证！请设置新的 PIN 码。",
        prompt_new_pin: "输入您的新 4 位数 PIN 码：",
        alert_pin_updated: "PIN 码已更新。正在进入...",
        alert_invalid_pin: "无效的 PIN 码。",
        alert_wrong_phrase: "短语错误。",
        audit_panel_title: "管理控制面板与成员",
        audit_full_access: "完全访问权限",
        audit_status_expelled: "已驱逐 / 已撤销",
        audit_status_active: "活跃",
        audit_btn_readmit: "重新接纳",
        audit_btn_expel: "驱逐",
        audit_director: "主管",
        audit_confirm_expel: "您确定要驱逐 ${nombreMiembro} 吗？其会话将立即关闭且无法访问。",
        chat_none_yet: "暂无",
        chat_audit_seen_by: "管理审计 - 已读：",
        chat_delete_title: "删除内容",
        chat_expires_in: "72小时后过期（自动销毁）",
        chat_secure_file: "安全文件",
        chat_transmitted: "已传输",
        viewer_zero_trace_img: "🛡️ 零追踪模式已激活：图像已受到保护，防止直接下载。",
        viewer_zero_trace_pdf: "🛡️ 零追踪模式已激活：文档查看仅限内存。",
        viewer_restricted_format: "该格式以受限制的方式显示。",
        recovery_placeholder: "单词1 单词2 单词3 单词4",
role_prefix: "角色：",
hide_tooltip: "快速锁定",
back_tooltip: "返回锁屏界面",
role_admin: "管理员 / 主管",
role_member: "成员",
btn_view: "查看",
btn_download: "下载",
label_identity: "您的身份名称（第一个配置的将成为管理员）",
placeholder_identity: "例如 LUNA 或 TIGRE"
    },
    ja: {
        page_title: "BENEATH - セキュアファイル＆管理コントロール // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "SASAグループへようこそ",
        welcome_desc: "保護および暗号化されたインフラストラクチャ。電話番号や個人情報は一切公開されません。",
        access_btn: "システムにアクセス",
        page_title: "BENEATH - セキュアファイル＆管理コントロール // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "保護された画面",
        curtain_desc: "オフィスの視覚的セキュリティのため、セッションが非表示になりました。",
        curtain_btn: "画面を復元",
        app_subtitle: "送信 • 一時ファイル • 監査",
        setup_title: "ローカルアイデンティティの作成",
        label_pin: "アクセスPINを定義（4桁）",
        setup_btn: "BENEATHの開始とキーの生成",
        active_identity_label: "アクティブID:",
        enter_pin_label: "PINを入力してください",
        unlock_pin_btn: "ロック解除 (PIN)",
        forgot_pin_link: "PINをお忘れですか？（リカバリフレーズ）",
        recovery_title: "ゼロ知識リカバリ",
        recovery_desc: "緊急シークレットフレーズを入力してください：",
        recovery_btn: "アクセスをリセット",
        hide_btn: "👁️ 隠す",
        back_btn: "🚪 戻る",
        active_groups_title: "アクティブグループ",
        group_desc_pesa: "統合セキュアチャネル (72時間)",
        enter_group_btn: "入室 &rarr;",
        back_to_groups_btn: "&larr; グループに戻る",
        audit_members_btn: "📊 監査とメンバー",
        msg_placeholder: "メッセージを入力またはリンクを貼り付け (Enter)...",
        send_btn: "送信",
        attach_file_label: "📎 ファイル / 写真 / PDF を添付 (アプリ内ビュー)",
        select_file_btn: "ファイルを選択",
        close_btn: "✕ 閉じる",
        alert_invalid_identity: "有効な識別名と正確に4桁のPINを入力してください。",
        alert_revoked: "管理者によってアクセスが取り消されました。",
        alert_identity_created: "IDが正常に作成されました！\n\n[ 緊急復元フレーズ ]\n次の4つの単語をメモしてください：\n\n--> ${frase} <--",
        alert_wrong_pin: "PINが間違っています。",
        alert_phrase_verified: "フレーズが確認されました！新しいPINを設定してください。",
        prompt_new_pin: "新しい4桁のPINを入力してください：",
        alert_pin_updated: "PINが更新されました。入室中...",
        alert_invalid_pin: "無効なPINです。",
        alert_wrong_phrase: "フレーズが間違っています。",
        audit_panel_title: "管理コントロールパネル＆メンバー",
        audit_full_access: "フルアクセス",
        audit_status_expelled: "追放 / 取消済み",
        audit_status_active: "アクティブ",
        audit_btn_readmit: "再承認",
        audit_btn_expel: "追放",
        audit_director: "ディレクター",
        audit_confirm_expel: "${nombreMiembro} を追放してもよろしいですか？セッションは直ちに終了し、アクセスできなくなります。",
        chat_none_yet: "まだなし",
        chat_audit_seen_by: "管理監査 - 既読：",
        chat_delete_title: "コンテンツを削除",
        chat_expires_in: "72時間後に期限切れ（自動消滅）",
        chat_secure_file: "セキュアファイル",
        chat_transmitted: "送信済み",
        viewer_zero_trace_img: "🛡️ ゼロトレースモード有効：直接ダウンロードから保護された画像。",
        viewer_zero_trace_pdf: "🛡️ ゼロトレースモード有効：ドキュメントの表示はメモリ内に制限されています。",
        viewer_restricted_format: "このフォーマットは制限された形式で表示されます。",
        recovery_placeholder: "ワード1 ワード2 ワード3 ワード4",
role_prefix: "ロール:",
hide_tooltip: "エクスプレスロック",
back_tooltip: "ロック画面に戻る",
role_admin: "管理者 / ディレクター",
role_member: "メンバー",
btn_view: "表示",
btn_download: "ダウンロード",
label_identity: "アイデンティティ名（最初に設定された人が管理者になります）",
placeholder_identity: "例: LUNA または TIGRE"
    },
    it: {
        page_title: "BENEATH - File Sicuri e Controllo Gestionale // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "Benvenuto nel Gruppo SASA",
        welcome_desc: "Infrastruttura protetta e crittografata. Nessun dato telefonico o personale viene esposto.",
        access_btn: "Accedi al Sistema",
        page_title: "BENEATH - File Sicuri e Controllo Gestionale // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "SCHERMO PROTETTO",
        curtain_desc: "La sessione è stata nascosta per sicurezza visiva in ufficio.",
        curtain_btn: "Ripristina Schermo",
        app_subtitle: "TRASMETTI • FILE EFEMERI • AUDITA",
        setup_title: "Crea Identità Locale",
        label_pin: "Definisci un PIN di accesso (4 cifre)",
        setup_btn: "Avvia BENEATH e Genera Chiavi",
        active_identity_label: "Identità attiva:",
        enter_pin_label: "Inserisci il tuo PIN",
        unlock_pin_btn: "Sblocca (PIN)",
        forgot_pin_link: "Hai dimenticato il PIN? (Frase di recupero)",
        recovery_title: "Recupero Zero-Knowledge",
        recovery_desc: "Inserisci la tua frase segreta di emergenza:",
        recovery_btn: "Ripristina Accesso",
        hide_btn: "👁️ Nascondi",
        back_btn: "🚪 Indietro",
        active_groups_title: "I tuoi gruppi attivi",
        group_desc_pesa: "Canale sicuro unificato (72h)",
        enter_group_btn: "Entra &rarr;",
        back_to_groups_btn: "&larr; Torna ai gruppi",
        audit_members_btn: "📊 Audit e Membri",
        msg_placeholder: "Scrivi un messaggio o incolla link (Enter)...",
        send_btn: "Invia",
        attach_file_label: "📎 Allega File / Foto / PDF (Vista In-App)",
        select_file_btn: "Seleziona File",
        close_btn: "✕ Chiudi",
        alert_invalid_identity: "Inserisci un'identità valida e un PIN esatto di 4 cifre.",
        alert_revoked: "Il tuo accesso è stato revokato dall'amministratore.",
        alert_identity_created: "Identità creata con successo!\n\n[ FRASE DI RECUPERO DI EMERGENZA ]\nAnnota queste 4 parole:\n\n--> ${frase} <--",
        alert_wrong_pin: "PIN errato.",
        alert_phrase_verified: "Frase verificata! Imposta un nuovo PIN.",
        prompt_new_pin: "Inserisci il tuo nuovo PIN di 4 cifre:",
        alert_pin_updated: "PIN aggiornato. Accesso in corso...",
        alert_invalid_pin: "PIN non valido.",
        alert_wrong_phrase: "Frase errata.",
        audit_panel_title: "Pannello di Controllo Manageriale e Membri",
        audit_full_access: "Accesso Totale",
        audit_status_expelled: "Espulso / Revocato",
        audit_status_active: "Attivo",
        audit_btn_readmit: "Riammaetti",
        audit_btn_expel: "Espelli",
        audit_director: "Direttore",
        audit_confirm_expel: "Sei sicuro di voler espellere ${nombreMiembro}? La sua sessione verrà chiusa immediatamente e non potrà accedere.",
        chat_none_yet: "Nessuno ancora",
        chat_audit_seen_by: "Audit Manageriale - Visto da:",
        chat_delete_title: "Elimina contenuto",
        chat_expires_in: "Scade in 72h (Autodistruzione)",
        chat_secure_file: "File Sicuro",
        chat_transmitted: "Trasmesso",
        viewer_zero_trace_img: "🛡️ Modalità Zero-Trace Attiva: Immagine protetta contro il download diretto.",
        viewer_zero_trace_pdf: "🛡️ Modalità Zero-Trace Attiva: Visualizzazione del documento limitata alla memoria.",
        viewer_restricted_format: "Questo formato viene visualizzato in modo limitato.",
        recovery_placeholder: "parola1 parola2 parola3 parola4",
role_prefix: "RUOLO:",
hide_tooltip: "Blocco Express",
back_tooltip: "Torna alla schermata di blocco",
role_admin: "AMMINISTRATORE / DIRETTORE",
role_member: "MEMBRO",
btn_view: "Visualizza",
btn_download: "Scarica",
label_identity: "Il tuo Nome Identità (Il primo configurato sarà Admin)",
placeholder_identity: "Es. LUNA o TIGRE"
    },
    hi: {
        page_title: "BENEATH - सुरक्षित फ़ाइलें और प्रबंधन नियंत्रण // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "SASA समूह में आपका स्वागत है",
        welcome_desc: "सुरक्षित और एन्क्रिप्टेड बुनियादी ढांचा। कोई भी टेलीफोन या व्यक्तिगत डेटा उजागर नहीं किया जाता है।",
        access_btn: "सिस्टम तक पहुंचें",
        page_title: "BENEATH - सुरक्षित फ़ाइलें और प्रबंधन नियंत्रण // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "सुरक्षित स्क्रीन",
        curtain_desc: "कार्यालय की दृश्य सुरक्षा के लिए सत्र छिपा दिया गया है।",
        curtain_btn: "स्क्रीन पुनर्स्थापित करें",
        app_subtitle: "ट्रांसफर • अल्पकालिक फ़ाइलें • ऑडिट",
        setup_title: "स्थानीय पहचान बनाएं",
        label_pin: "एक्सेस पिन निर्धारित करें (4 अंक)",
        setup_btn: "BENEATH शुरू करें और कुंजियां जेनरेट करें",
        page_title: "BENEATH - सुरक्षित फ़ाइलें और प्रबंधन नियंत्रण // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "सुरक्षित स्क्रीन",
        curtain_desc: "कार्यालय की दृश्य सुरक्षा के लिए सत्र छिपा दिया गया है।",
        curtain_btn: "स्क्रीन पुनर्स्थापित करें",
        app_subtitle: "ट्रांसफर • अल्पकालिक फ़ाइलें • ऑडिट",
        setup_title: "स्थानीय पहचान बनाएं",
        label_pin: "एक्सेस पिन निर्धारित करें (4 अंक)",
        setup_btn: "BENEATH शुरू करें और कुंजियां जेनरेट करें",
        active_identity_label: "सक्रिय पहचान:",
        enter_pin_label: "अपना पिन दर्ज करें",
        unlock_pin_btn: "अनलॉक करें (पिन)",
        forgot_pin_link: "पिन भूल गए? (पुनप्राप्ति वाक्यांश)",
        recovery_title: "जीरो-नॉलेज रिकवरी",
        recovery_desc: "अपना आपातकालीन गुप्त वाक्यांश दर्ज करें:",
        recovery_btn: "पहुँच रीसेट करें",
        hide_btn: "👁️ छिपाएँ",
        back_btn: "🚪 पीछे",
        active_groups_title: "आपके सक्रिय समूह",
        group_desc_pesa: "एकीकृत सुरक्षित चैनल (72h)",
        enter_group_btn: "प्रवेश करें &rarr;",
        back_to_groups_btn: "&larr; समूहों पर वापस जाएं",
        audit_members_btn: "📊 ऑडिट और सदस्य",
        msg_placeholder: "संदेश लिखें या लिंक पेस्ट करें (Enter)...",
        send_btn: "भेजें",
        attach_file_label: "📎 फ़ाइल / फ़ोटो / पीडीएफ संलग्न करें (इन-ऐप)",
        select_file_btn: "फ़ाइल चुनें",
        close_btn: "✕ बंद करें",
        alert_invalid_identity: "कृपया एक वैध पहचान और सटीक 4-अंकों का पिन दर्ज करें।",
        alert_revoked: "प्रशासक द्वारा आपकी पहुंच रद्द कर दी गई है।",
        alert_identity_created: "पहचान सफलतापूर्वक बनाई गई!\n\n[ आपातकालीन पुनर्प्राप्ति वाक्यांश ]\nइन 4 शब्दों को नोट करें:\n\n--> ${frase} <--",
        alert_wrong_pin: "गलत पिन।",
        alert_phrase_verified: "वाक्यश सत्यापित! एक नया पिन सेट करें।",
        prompt_new_pin: "अपना नया 4-अंकों का पिन दर्ज करें:",
        alert_pin_updated: "पिन अपडेट किया गया। प्रवेश कर रहे हैं...",
        alert_invalid_pin: "अमान्य पिन।",
        alert_wrong_phrase: "गलत वाक्यांश।",
        audit_panel_title: "प्रबंधन नियंत्रण कक्ष और सदस्य",
        audit_full_access: "पूर्ण पहुंच",
        audit_status_expelled: "निष्कासित / रद्द",
        audit_status_active: "सक्रिय",
        audit_btn_readmit: "पुनः प्रवेश दें",
        audit_btn_expel: "निष्कासित करें",
        audit_director: "निदेशक",
        audit_confirm_expel: "क्या आप वाकई ${nombreMiembro} को निष्कासित करना चाहते हैं? उनका सत्र तुरंत समाप्त हो जाएगा और वे एक्सेस नहीं कर पाएंगे।",
        chat_none_yet: "अभी तक कोई नहीं",
        chat_audit_seen_by: "प्रबंधन ऑडिट - देखा गया:",
        chat_delete_title: "सामग्री हटाएं",
        chat_expires_in: "72 घंटे में समाप्त (स्वयं-विनाश)",
        chat_secure_file: "सुरक्षित फ़ाइल",
        chat_transmitted: "प्रसारित",
        viewer_zero_trace_img: "🛡️ ज़ीरो-ट्रेस मोड सक्रिय: प्रत्यक्ष डाउनलोड से सुरक्षित छवि।",
        viewer_zero_trace_pdf: "🛡️ ज़ीरो-ट्रेस मोड सक्रिय: दस्तावेज़ देखना मेमोरी तक सीमित है।",
        viewer_restricted_format: "यह प्रारूप प्रतिबंधित तरीके से प्रदर्शित किया जाता है।",
        recovery_placeholder: "शब्द1 शब्द2 शब्द3 शब्द4",
role_prefix: "भूमिका:",
hide_tooltip: "एक्सप्रेस लॉक",
back_tooltip: "लॉक स्क्रीन पर वापस जाएं",
role_admin: "प्रशासक / निदेशक",
role_member: "सदस्य",
btn_view: "देखें",
btn_download: "डाउनलोड",
label_identity: "आपकी पहचान का नाम (पहला कॉन्फ़िगर किया गया व्यवस्थापक होगा)",
placeholder_identity: "उदा. LUNA या TIGRE"
    },
    ar: {
        page_title: "BENEATH - الملفات الآمنة وإدارة التحكم // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "مرحباً بك في مجموعة SASA",
        welcome_desc: "بنية تحتية محمية ومشفرة. لا يتم الكشف عن أي بيانات هاتفية أو شخصية.",
        access_btn: "الوصول إلى النظام",
        page_title: "BENEATH - الملفات الآمنة وإدارة التحكم // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "شاشة محمية",
        curtain_desc: "تم إخفاء الجلسة لأسباب تتعلق بالسلامة البصرية في المكتب.",
        curtain_btn: "استعادة الشاشة",
        app_subtitle: "نقل • ملفات مؤقتة • تدقيق",
        setup_title: "إنشاء هوية محلية",
        label_pin: "حدد رقم تعريف شخصي PIN (4 أرقام)",
        setup_btn: "ابدأ BENEATH وقم بتوليد المفاتيح",
        active_identity_label: "الهوية النشطة:",
        enter_pin_label: "أدخل رقم التعريف الشخصي (PIN)",
        unlock_pin_btn: "فتح القفل (PIN)",
        forgot_pin_link: "هل نسيت رقم التعريف الشخصي؟ (عبارة الاسترداد)",
        recovery_title: "استرداد المعرفة الصفرية",
        recovery_desc: "أدخل عبارتك السرية للطوارئ:",
        recovery_btn: "إعادة تعيين الوصول",
        hide_btn: "👁️ إخفاء",
        back_btn: "🚪 رجوع",
        active_groups_title: "مجموعاتك النشطة",
        group_desc_pesa: "قناة آمنة موحدة (72 ساعة)",
        enter_group_btn: "دخول &rarr;",
        back_to_groups_btn: "&larr; العودة إلى المجموعات",
        audit_members_btn: "📊 التدقيق والأعضاء",
        msg_placeholder: "اكتب رسالة أو الصق رابطاً (Enter)...",
        send_btn: "إرسال",
        attach_file_label: "📎 إرفاق ملف / صورة / PDF (عرض داخل التطبيق)",
        select_file_btn: "اختر ملفاً",
        close_btn: "✕ إغلاق",
        alert_invalid_identity: "الرجاء إدخال هوية صالحة ورقم تعريف شخصي (PIN) مكون من 4 أرقام بدقة.",
        alert_revoked: "تم إلغاء حق الوصول الخاص بك من قبل المسؤول.",
        alert_identity_created: "تم إنشاء الهوية بنجاح!\n\n[ عبارة الاسترداد الطارئة ]\nقم بتدوين هذه الكلمات الأربع:\n\n--> ${frase} <--",
        alert_wrong_pin: "رقم تعريف شخصي (PIN) غير صحيح.",
        alert_phrase_verified: "تم التحقق من العبارة! تعيين رقم تعريف شخصي جديد.",
        prompt_new_pin: "أدخل رقم التعريف الشخصي الجديد المكون من 4 أرقام:",
        alert_pin_updated: "تم تحديث PIN. جاري الدخول...",
        alert_invalid_pin: "رقم تعريف شخصي غير صالح.",
        alert_wrong_phrase: "عبارة غير صحيحة.",
        audit_panel_title: "لوحة تحكم الإدارة والأعضاء",
        audit_full_access: "وصول كامل",
        audit_status_expelled: "مطرود / ملغي",
        audit_status_active: "نشط",
        audit_btn_readmit: "إعادة قبول",
        audit_btn_expel: "طرد",
        audit_director: "المدير",
        audit_confirm_expel: "هل أنت متأكد من طرد ${nombreMiembro}؟ سيتم إغلاق جلسته على الفور ولن يتمكن من الوصول.",
        chat_none_yet: "لا أحد بعد",
        chat_audit_seen_by: "تدقيق الإدارة - تمت رؤيته بواسطة:",
        chat_delete_title: "حذف المحتوى",
        chat_expires_in: "ينتهي خلال 72 ساعة (تدمير ذاتي)",
        chat_secure_file: "ملف آمن",
        chat_transmitted: "تم الإرسال",
        viewer_zero_trace_img: "🛡️ وضع التتبع الصفري نشط: الصورة محمية ضد التنزيل المباشر.",
        viewer_zero_trace_pdf: "🛡️ وضع التتبع الصفري نشط: عرض المستند مقيد بالذاكرة.",
        viewer_restricted_format: "يتم عرض هذا التنسيق بطريقة مقيدة.",
        recovery_placeholder: "كلمة1 كلمة2 كلمة3 كلمة4",
role_prefix: "الدور:",
hide_tooltip: "قفل سريع",
back_tooltip: "العودة إلى شاشة القفل",
role_admin: "مدير / مخرج",
role_member: "عضو",
btn_view: "عرض",
btn_download: "تحميل",
label_identity: "اسم هويتك (الأول الذي يتم تكوينه سيكون مسؤولاً)",
placeholder_identity: "مثال: LUNA أو TIGRE"
    },
    tr: {
        page_title: "BENEATH - Güvenli Dosyalar ve Yönetim Kontrolü // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "SASA Grubuna Hoş Geldiniz",
        welcome_desc: "Korumalı ve şifrelenmiş altyapı. Hiçbir telefon veya kişisel veri ifşa edilmez.",
        access_btn: "Sisteme Eriş",
        page_title: "BENEATH - Güvenli Dosyalar ve Yönetim Kontrolü // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "KORUMALI EKRAN",
        curtain_desc: "Oturum, ofis görsel güvenliği için gizlendi.",
        curtain_btn: "Ekranı Geri Yükle",
        app_subtitle: "AKTAR • GEÇİCİ DOSYALAR • DENETLE",
        setup_title: "Yerel Kimlik Oluştur",
        label_pin: "Bir Erişim PIN'i Belirleyin (4 hane)",
        setup_btn: "BENEATH'i Başlat ve Anahtar Üret",
        active_identity_label: "Aktif Kimlik:",
        enter_pin_label: "PIN kodunuzu girin",
        unlock_pin_btn: "Kilidi Aç (PIN)",
        forgot_pin_link: "PIN'inizi mi unuttunuz? (Kurtarma İfadesi)",
        recovery_title: "Sıfır Bilgi Kurtarma",
        recovery_desc: "Acil durum gizli ifadenizi girin:",
        recovery_btn: "Erişimi Sıfırla",
        hide_btn: "👁️ Gizle",
        back_btn: "🚪 Geri",
        active_groups_title: "Aktif Gruplarınız",
        group_desc_pesa: "Birleşik Güvenli Kanal (72s)",
        enter_group_btn: "Giriş &rarr;",
        back_to_groups_btn: "&larr; Gruplara Dön",
        audit_members_btn: "📊 Denetim & Üyeler",
        msg_placeholder: "Mesaj yazın veya bağlantı yapıştırın (Enter)...",
        send_btn: "Gönder",
        attach_file_label: "📎 Dosya / Fotoğraf / PDF Ekle (Uygulama İçi Görünüm)",
        select_file_btn: "Dosya Seç",
        close_btn: "✕ Kapat",
        alert_invalid_identity: "Lütfen geçerli bir kimlik ve tam 4 haneli bir PIN girin.",
        alert_revoked: "Erişiminiz yönetici tarafından iptal edildi.",
        alert_identity_created: "Kimlik başarıyla oluşturuldu!\n\n[ ACİL KURTARMA İFADESİ ]\nBu 4 kelimeyi bir yere not edin:\n\n--> ${frase} <--",
        alert_wrong_pin: "Hatalı PIN.",
        alert_phrase_verified: "İfade doğrulandı! Yeni bir PIN belirleyin.",
        prompt_new_pin: "Yeni 4 haneli PIN'inizi girin:",
        alert_pin_updated: "PIN güncellendi. Giriş yapılıyor...",
        alert_invalid_pin: "Geçersiz PIN.",
        alert_wrong_phrase: "Yanlış ifade.",
        audit_panel_title: "Yönetim Kontrol Paneli ve Üyeler",
        audit_full_access: "Tam Erişim",
        audit_status_expelled: "İhraç Edildi / İptal Edildi",
        audit_status_active: "Aktif",
        audit_btn_readmit: "Tekrar Kabul Et",
        audit_btn_expel: "İhraç Et",
        audit_director: "Yönetici",
        audit_confirm_expel: "${nombreMiembro} adlı üyeyi ihraç etmek istediğinizden emin misiniz? Oturumu derhal kapatılacak ve erişemeyecektir.",
        chat_none_yet: "Henüz yok",
        chat_audit_seen_by: "Yönetim Denetimi - Gorenler:",
        chat_delete_title: "İçeriği sil",
        chat_expires_in: "72 saat içinde sona erer (Kendi kendine imha)",
        chat_secure_file: "Güvenli Dosya",
        chat_transmitted: "İletildi",
        viewer_zero_trace_img: "🛡️ Sıfır İz Modu Aktif: Doğrudan indirmeye karşı korunan görsel.",
        viewer_zero_trace_pdf: "🛡️ Sıfır İz Modu Aktif: Belge görüntüleme bellekle sınırlıdır.",
        viewer_restricted_format: "Bu format kısıtlı bir şekilde görüntülenmektedir.",
        recovery_placeholder: "kelime1 kelime2 kelime3 kelime4",
role_prefix: "ROL:",
hide_tooltip: "Hızlı Kilitleme",
back_tooltip: "Kilit ekranına dön",
role_admin: "YÖNETİCİ / DİREKTÖR",
role_member: "ÜYE",
btn_view: "Gör",
btn_download: "İndir",
label_identity: "Kimlik Adınız (İlk yapılandırılan Yönetici olacaktır)",
placeholder_identity: "Örn. LUNA veya TIGRE"
        
    },
    ru: {
        page_title: "BENEATH - Безопасные файлы и управленческий контроль // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "Добро пожаловать в группу SASA",
        welcome_desc: "Защищенная и зашифрованная инфраструктура. Никакие телефонные или личные данные не разглашаются.",
        access_btn: "Войти в систему",
        page_title: "BENEATH - Безопасные файлы и управленческий контроль // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "ЗАЩИЩЕННЫЙ ЭКРАН",
        curtain_desc: "Сеанс был скрыт в целях визуальной безопасности в офисе.",
        curtain_btn: "Восстановить экран",
        app_subtitle: "ПЕРЕДАВАТЬ • ВРЕМЕННЫЕ ФАЙЛЫ • АУДИТ",
        setup_title: "Создать локальную идентификацию",
        label_pin: "Задайте PIN-код доступа (4 цифры)",
        setup_btn: "Запустить BENEATH и сгенерировать ключи",
        active_identity_label: "Активный профиль:",
        enter_pin_label: "Введите ваш PIN-код",
        unlock_pin_btn: "Разблокировать (PIN)",
        forgot_pin_link: "Забыли PIN-код? (Фраза восстановления)",
        recovery_title: "Восстановление с нулевым разглашением",
        recovery_desc: "Введите вашу секретную фразу экстренного восстановления:",
        recovery_btn: "Сбросить доступ",
        hide_btn: "👁️ Скрыть",
        back_btn: "🚪 Назад",
        active_groups_title: "Ваши активные группы",
        group_desc_pesa: "Единый защищенный канал (72ч)",
        enter_group_btn: "Войти &rarr;",
        back_to_groups_btn: "&larr; Назад к группам",
        audit_members_btn: "📊 Аудит и участники",
        msg_placeholder: "Введите сообщение или ссылку (Enter)...",
        send_btn: "Отправить",
        attach_file_label: "📎 Прикрепить файл / фото / PDF (В приложении)",
        select_file_btn: "Выбрать файл",
        close_btn: "✕ Закрыть",
        alert_invalid_identity: "Пожалуйста, введите действительный профиль и ровно 4-значный PIN-код.",
        alert_revoked: "Ваш доступ был отозван администратором.",
        alert_identity_created: "Профиль успешно создан!\n\n[ ФРАЗА АВАРИЙНОГО ВОССТАНОВЛЕНИЯ ]\nЗапишите эти 4 слова:\n\n--> ${frase} <--",
        alert_wrong_pin: "Неверный PIN-код.",
        alert_phrase_verified: "Фраза подтверждена! Установите новый PIN-код.",
        prompt_new_pin: "Введите новый 4-значный PIN-код:",
        alert_pin_updated: "PIN обновлен. Вход...",
        alert_invalid_pin: "Неверный PIN-код.",
        alert_wrong_phrase: "Неверная фраза.",
        audit_panel_title: "Панель управления и участники",
        audit_full_access: "Полный доступ",
        audit_status_expelled: "Исключен / Отозван",
        audit_status_active: "Активен",
        audit_btn_readmit: "Восстановить",
        audit_btn_expel: "Исключить",
        audit_director: "Директор",
        audit_confirm_expel: "Вы уверены, что хотите исключить ${nombreMiembro}? Его сеанс будет немедленно завершен, и доступ будет заблокирован.",
        chat_none_yet: "Пока нет",
        chat_audit_seen_by: "Управленческий аудит - Просмотрено:",
        chat_delete_title: "Удалить контент",
        chat_expires_in: "Истекает через 72 часа (Самоуничтожение)",
        chat_secure_file: "Защищенный файл",
        chat_transmitted: "Передано",
        viewer_zero_trace_img: "🛡️ Режим Zero-Trace активен: Изображение защищено от прямой загрузки.",
        viewer_zero_trace_pdf: "🛡️ Режим Zero-Trace активен: Просмотр документов ограничен памятью.",
        viewer_restricted_format: "Этот формат отображается в ограниченном режиме.",
        recovery_placeholder: "слово1 слово2 слово3 слово4",
role_prefix: "РОЛЬ:",
hide_tooltip: "Быстрая блокировка",
back_tooltip: "Вернуться на экран блокировки",
role_admin: "АДМИНИСТРАТОР / ДИРЕКТОР",
role_member: "УЧАСТНИК",
btn_view: "Смотреть",
btn_download: "Скачать",
label_identity: "Ваше имя идентичности (Первое настроенное будет администратором)",
placeholder_identity: "Пр. LUNA или TIGRE"
        
    },
    sv: {
        page_title: "BENEATH - Säkra filer & managementkontroll // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "Välkommen till SASA-gruppen",
        welcome_desc: "Skyddad och krypterad infrastruktur. Inga telefon- eller personuppgifter exponeras.",
        access_btn: "Gå till systemet",
        page_title: "BENEATH - Säkra filer & managementkontroll // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "SKYDDAD SKÄRM",
        curtain_desc: "Sessionen har dolda av visuell säkerhet på kontoret.",
        curtain_btn: "Återställ skärm",
        app_subtitle: "ÖVERFÖRA • EFEMÄRA FILER • REVIDERA",
        setup_title: "Skapa lokal identitet",
        label_pin: "Definiera en åtkomst-PIN (4 siffror)",
        setup_btn: "Starta BENEATH och generera nycklar",
        active_identity_label: "Aktiv identitet:",
        enter_pin_label: "Ange din PIN-kod",
        unlock_pin_btn: "Lås upp (PIN)",
        forgot_pin_link: "Glömt din PIN? (Återställningsfras)",
        recovery_title: "Nollkunskapsåterställning",
        recovery_desc: "Ange din hemliga nödlägesfras:",
        recovery_btn: "Återställ åtkomst",
        hide_btn: "👁️ Dölj",
        back_btn: "🚪 Tillbaka",
        active_groups_title: "Dina aktiva grupper",
        group_desc_pesa: "Unified Secure Channel (72h)",
        enter_group_btn: "Gå in &rarr;",
        back_to_groups_btn: "&larr; Tillbaka till grupper",
        audit_members_btn: "📊 Revision & Medlemmar",
        msg_placeholder: "Skriv meddelande eller klistra in länk (Enter)...",
        send_btn: "Skicka",
        attach_file_label: "📎 Bifoga fil / foto / PDF (In-App-vy)",
        select_file_btn: "Välj fil",
        close_btn: "✕ Stäng",
        alert_invalid_identity: "Ange en giltig identitet och en exakt 4-siffrig PIN-kod.",
        alert_revoked: "Din åtkomst har återkallats av administratören.",
        alert_identity_created: "Identitet skapad framgångsrikt!\n\n[ NÖDÅTERSTÄLLNINGSFRAS ]\nSkriv ner dessa 4 ord:\n\n--> ${frase} <--",
        alert_wrong_pin: "Felaktig PIN.",
        alert_phrase_verified: "Fras verifierad! Ställ in en ny PIN.",
        prompt_new_pin: "Ange din nya 4-siffriga PIN:",
        alert_pin_updated: "PIN uppdaterad. Loggar in...",
        alert_invalid_pin: "Ogiltig PIN.",
        alert_wrong_phrase: "Felaktig fras.",
        audit_panel_title: "Ledningskontrollpanel & Medlemmar",
        audit_full_access: "Full åtkomst",
        audit_status_expelled: "Utstött / Återkallad",
        audit_status_active: "Aktiv",
        audit_btn_readmit: "Återanta",
        audit_btn_expel: "Uteslut",
        audit_director: "Direktör",
        audit_confirm_expel: "Är du säker på att du vill utesluta ${nombreMiembro}? Deras session kommer att stängas omedelbart och de kan inte komma åt.",
        chat_none_yet: "Ingen ännu",
        chat_audit_seen_by: "Ledningsrevision - Sedd av:",
        chat_delete_title: "Ta bort innehåll",
        chat_expires_in: "Utgår om 72h (Självförstörelse)",
        chat_secure_file: "Säker fil",
        chat_transmitted: "Överförd",
        viewer_zero_trace_img: "🛡️ Zero-Trace-läge aktivt: Bild skyddad mot direkt nedladdning.",
        viewer_zero_trace_pdf: "🛡️ Zero-Trace-läge aktivt: Dokumentvisning begränsad till minnet.",
        viewer_restricted_format: "Detta format visas på ett begränsat sätt.",
        recovery_placeholder: "ord1 ord2 ord3 ord4",
role_prefix: "ROLL:",
hide_tooltip: "Snabb låsning",
back_tooltip: "Tillbaka till låsskärmen",
role_admin: "ADMIN / DIREKTÖR",
role_member: "MEDLEM",
btn_view: "Visa",
btn_download: "Ladda ner",
label_identity: "Ditt identitetsnamn (Den första som konfigureras blir Admin)",
placeholder_identity: "Ex. LUNA eller TIGRE"
    },
    nl: {
        page_title: "BENEATH - Veilige Bestanden & Beheerscontrole // SASA",
        logo_text: "BENEATH // SASA",
        welcome_title: "Welkom bij de SASA Groep",
        welcome_desc: "Beschermde en versleutelde infrastructuur. Geen telefoon- of persoonsgegevens worden blootgesteld.",
        access_btn: "Systeem openen",
        page_title: "BENEATH - Veilige Bestanden & Beheerscontrole // SASA",
        logo_text: "BENEATH // SASA",
        curtain_title: "BESCHERMD SCHERM",
        curtain_desc: "De sessie is verborgen omwille van visuele beveiliging op kantoor.",
        curtain_btn: "Scherm Herstellen",
        app_subtitle: "VERZENDEN • EFEMERE BESTANDEN • AUDIT",
        setup_title: "Lokale Identiteit Aanmaken",
        label_pin: "Definieer een Pincode (4 cijfers)",
        setup_btn: "Start BENEATH en Genereer Sleutels",
        active_identity_label: "Actieve identiteit:",
        enter_pin_label: "Voer je Pincode in",
        unlock_pin_btn: "Ontgrendelen (PIN)",
        forgot_pin_link: "Pincode vergeten? (Herstelzin)",
        recovery_title: "Zero-Knowledge Herstel",
        recovery_desc: "Voer je geheime noodzin in:",
        recovery_btn: "Toegang Resetten",
        hide_btn: "👁️ Verbergen",
        back_btn: "🚪 Terug",
        active_groups_title: "Jouw Actieve Groepen",
        group_desc_pesa: "Geïntegreerd Veilig Kanaal (72u)",
        enter_group_btn: "Openen &rarr;",
        back_to_groups_btn: "&larr; Terug naar Groepen",
        audit_members_btn: "📊 Audit & Leden",
        msg_placeholder: "Typ bericht of plak link (Enter)...",
        send_btn: "Verzenden",
        attach_file_label: "📎 Bestand / Foto / PDF bijvoegen (In-App weergave)",
        select_file_btn: "Bestand Selecteren",
        close_btn: "✕ Sluiten",
        alert_invalid_identity: "Voer een geldige identiteit en een exacte pincode van 4 cijfers in.",
        alert_revoked: "Je toegang is ingetrokken door de beheerder.",
        alert_identity_created: "Identiteit succesvol aangemaakt!\n\n[ NOODHERSTELZIN ]\nNoteer deze 4 woorden:\n\n--> ${frase} <--",
        alert_wrong_pin: "Onjuiste pincode.",
        alert_phrase_verified: "Zin geverifieerd! Stel een nieuwe pincode in.",
        prompt_new_pin: "Voer je nieuwe pincode van 4 cijfers in:",
        alert_pin_updated: "Pincode bijgewerkt. Bezig met inloggen...",
        alert_invalid_pin: "Ongeldige pincode.",
        alert_wrong_phrase: "Onjuiste zin.",
        audit_panel_title: "Management Bedieningspaneel & Leden",
        audit_full_access: "Volledige Toegang",
        audit_status_expelled: "Uitgesloten / Ingetrokken",
        audit_status_active: "Actief",
        audit_btn_readmit: "Herstellen",
        audit_btn_expel: "Uitsluiten",
        audit_director: "Directeur",
        audit_confirm_expel: "Weet je zeker dat je ${nombreMiembro} wilt uitsluiten? Hun sessie wird onmiddellijk beëindigd en ze hebben geen toegang meer.",
        chat_none_yet: "Nog geen",
        chat_audit_seen_by: "Management Audit - Gezien door:",
        chat_delete_title: "Inhoud verwijderen",
        chat_expires_in: "Verloopt over 72u (Zelfvernietiging)",
        chat_secure_file: "Veilig Bestand",
        chat_transmitted: "Overgedragen",
        viewer_zero_trace_img: "🛡️ Zero-Trace Modus Actief: Afbeelding beschermd tegen direct downloaden.",
        viewer_zero_trace_pdf: "🛡️ Zero-Trace Modus Actief: Documentweergave beperkt tot het geheugen.",
        viewer_restricted_format: "Dit formaat wordt op een beperkte manier weergegeven.",
        recovery_placeholder: "woord1 woord2 woord3 woord4",
role_prefix: "ROL:",
hide_tooltip: "Snelle Vergrendeling",
back_tooltip: "Terug naar vergrendelscherm",
role_admin: "ADMIN / DIRECTEUR",
role_member: "LID",
btn_view: "Bekijken",
btn_download: "Downloaden",
label_identity: "Uw Identiteitsnaam (De als eerste geconfigureerde wordt Admin)",
placeholder_identity: "Bijv. LUNA of TIGRE"
    }
};

function cambiarIdioma(lang) {
    if (!DICTIONARY[lang]) return;
    
    // Guardar preferencia
    localStorage.setItem('sipv_lang', lang);
    
    // Actualizar elementos data-i18n
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (DICTIONARY[lang][key]) {
            el.innerText = DICTIONARY[lang][key];
        }
    });

    // NUEVO: Actualizar los placeholders de los inputs (Ej. LUNA o TIGRE)
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (DICTIONARY[lang][key]) {
            el.placeholder = DICTIONARY[lang][key];
        }
    });

    // Sincroniza configuraciones externas si existen
    if (typeof CONFIG !== 'undefined' && CONFIG.textos) {
        ['cat1', 'cat2', 'cat3'].forEach(cat => {
            if (DICTIONARY[lang][cat + '_t']) CONFIG.textos[cat].t = DICTIONARY[lang][cat + '_t'];
            if (DICTIONARY[lang][cat + '_c']) CONFIG.textos[cat].c = DICTIONARY[lang][cat + '_c'];
        });
    }
}

document.addEventListener("DOMContentLoaded", () => {
    const langGuardado = localStorage.getItem('sipv_lang') || 'es';
    cambiarIdioma(langGuardado);
    
    const selector = document.getElementById('cambiador-idioma');
    if (selector) {
        selector.value = langGuardado;
        selector.addEventListener('change', (e) => cambiarIdioma(e.target.value));
    }
});